apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-study-app
spec:
  selector:
    matchLabels:
      app: k8s-study-app
  template:
    spec:
      containers:
        - name: k8s-study-app
          image: andrewromanchukk/k8s-study-app:1.0.1
          ports:
            - containerPort: 8089
